services:
  adimeo_data_suite_es_server:
    class: AdimeoDataSuite\Bundle\CommonsBundle\Index\IndexManager
    arguments: ["%env(ELASTICSEARCH_SERVER_URL)%", "@security.password_encoder"]
    public: true